/* ============================================================
   playlists-rdm.js  — AUTO-GENERATED by dev/migrate-playlists.js
   12 playlists migrated from the old data.js, re-keyed to the
   stable .musicxml filename so they survive data-rdm.js rebuilds.
   Schema per item: { file, name, tempos:[], repetitionsPerTempo }
   Re-run the migration script to regenerate; do not hand-edit.
   ============================================================ */
window.PLAYLISTS_RDM = [
  {
    "name": "5 Fundamentals Easy",
    "items": [
      {
        "file": "Eights.musicxml",
        "name": "Eights",
        "tempos": [
          100,
          120,
          140,
          160,
          180,
          200
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Bucks.musicxml",
        "name": "Bucks",
        "tempos": [
          100,
          110,
          120
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Bucks.musicxml",
        "name": "Bucks",
        "tempos": [
          130,
          140
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          90,
          100,
          110
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          120,
          130
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Huggadics.musicxml",
        "name": "Huggadics",
        "tempos": [
          80,
          90,
          100,
          110
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Huckgadics.musicxml",
        "name": "Huckgadics",
        "tempos": [
          70,
          85,
          100,
          120
        ],
        "repetitionsPerTempo": 4
      }
    ]
  },
  {
    "name": "5 Fundamentals Hard",
    "items": [
      {
        "file": "Eights.musicxml",
        "name": "Eights",
        "tempos": [
          150,
          170,
          190,
          210,
          230,
          250
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Bucks.musicxml",
        "name": "Bucks",
        "tempos": [
          120,
          135,
          150
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Bucks.musicxml",
        "name": "Bucks",
        "tempos": [
          165,
          180
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          120,
          130,
          140
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          150,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Huggadics.musicxml",
        "name": "Huggadics",
        "tempos": [
          100,
          110,
          120,
          130
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Huckgadics.musicxml",
        "name": "Huckgadics",
        "tempos": [
          90,
          110,
          130,
          150
        ],
        "repetitionsPerTempo": 4
      }
    ]
  },
  {
    "name": "Flams Easy",
    "items": [
      {
        "file": "Flams - Flam Taps.musicxml",
        "name": "Flams - Flam Taps",
        "tempos": [
          110,
          120,
          130
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Flams - Flam Taps.musicxml",
        "name": "Flams - Flam Taps",
        "tempos": [
          140,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flams - Swisses.musicxml",
        "name": "Flams - Swisses",
        "tempos": [
          110,
          120,
          130
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Flams - Swisses.musicxml",
        "name": "Flams - Swisses",
        "tempos": [
          140,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flam Accent Builder.musicxml",
        "name": "Flam Accent Builder",
        "tempos": [
          105,
          120
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flam Accent Builder.musicxml",
        "name": "Flam Accent Builder",
        "tempos": [
          135,
          150
        ],
        "repetitionsPerTempo": 2
      },
      {
        "file": "Add A Flam.musicxml",
        "name": "Add A Flam",
        "tempos": [
          70,
          80,
          90
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Add A Flam.musicxml",
        "name": "Add A Flam",
        "tempos": [
          100,
          110
        ],
        "repetitionsPerTempo": 2
      },
      {
        "file": "Flam Tap Builder.musicxml",
        "name": "Flam Tap Builder",
        "tempos": [
          80,
          90,
          100
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flam Tap Builder.musicxml",
        "name": "Flam Tap Builder",
        "tempos": [
          110
        ],
        "repetitionsPerTempo": 2
      },
      {
        "file": "Swiss Taps.musicxml",
        "name": "Swiss Taps",
        "tempos": [
          80,
          90,
          100,
          110
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Flams Hard",
    "items": [
      {
        "file": "Flams - Flam Taps.musicxml",
        "name": "Flams - Flam Taps",
        "tempos": [
          130,
          145,
          160
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Flams - Flam Taps.musicxml",
        "name": "Flams - Flam Taps",
        "tempos": [
          175,
          190
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flams - Swisses.musicxml",
        "name": "Flams - Swisses",
        "tempos": [
          130,
          145,
          160
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Flams - Swisses.musicxml",
        "name": "Flams - Swisses",
        "tempos": [
          175,
          190
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flam Accent Builder.musicxml",
        "name": "Flam Accent Builder",
        "tempos": [
          135,
          140
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flam Accent Builder.musicxml",
        "name": "Flam Accent Builder",
        "tempos": [
          155,
          170
        ],
        "repetitionsPerTempo": 2
      },
      {
        "file": "Add A Flam.musicxml",
        "name": "Add A Flam",
        "tempos": [
          100,
          110,
          120
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Add A Flam.musicxml",
        "name": "Add A Flam",
        "tempos": [
          130,
          140
        ],
        "repetitionsPerTempo": 2
      },
      {
        "file": "Flam Tap Builder.musicxml",
        "name": "Flam Tap Builder",
        "tempos": [
          100,
          110,
          120
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Flam Tap Builder.musicxml",
        "name": "Flam Tap Builder",
        "tempos": [
          130
        ],
        "repetitionsPerTempo": 2
      },
      {
        "file": "Swiss Taps.musicxml",
        "name": "Swiss Taps",
        "tempos": [
          105,
          120,
          135,
          150
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Modulations Easy",
    "items": [
      {
        "file": "Quarter Triplet - Triplet.musicxml",
        "name": "Quarter Triplet - Triplet",
        "tempos": [
          120,
          140,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Quarter Triplet - 16th.musicxml",
        "name": "Quarter Triplet - 16th",
        "tempos": [
          120,
          140,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th - Triplet.musicxml",
        "name": "8th - Triplet",
        "tempos": [
          120,
          140,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th - 16th.musicxml",
        "name": "8th - 16th",
        "tempos": [
          130,
          150,
          170
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet - 16th.musicxml",
        "name": "Triplet - 16th",
        "tempos": [
          120,
          140,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet - 9let.musicxml",
        "name": "Triplet - 9let",
        "tempos": [
          110,
          130,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th - 5let.musicxml",
        "name": "16th - 5let",
        "tempos": [
          110,
          130,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th - 6let.musicxml",
        "name": "16th - 6let",
        "tempos": [
          100,
          120,
          140
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th - 5let.musicxml",
        "name": "8th - 5let",
        "tempos": [
          110,
          130,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th - 6let.musicxml",
        "name": "8th - 6let",
        "tempos": [
          100,
          120,
          140
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Modulations Hard",
    "items": [
      {
        "file": "Quarter Triplet - 8th.musicxml",
        "name": "Quarter Triplet - 8th",
        "tempos": [
          160,
          180,
          200
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Quarter Triplet - 9let.musicxml",
        "name": "Quarter Triplet - 9let",
        "tempos": [
          120,
          140,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th - 8th 5let.musicxml",
        "name": "8th - 8th 5let",
        "tempos": [
          120,
          150,
          180
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th - 8th 9let.musicxml",
        "name": "8th - 8th 9let",
        "tempos": [
          160,
          180,
          200
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th 5let - Triplet.musicxml",
        "name": "8th 5let - Triplet",
        "tempos": [
          120,
          150,
          180
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th 5let - 16th.musicxml",
        "name": "8th 5let - 16th",
        "tempos": [
          120,
          140,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "8th 5let - 5let.musicxml",
        "name": "8th 5let - 5let",
        "tempos": [
          100,
          125,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet - 5let.musicxml",
        "name": "Triplet - 5let",
        "tempos": [
          110,
          130,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet - 6let.musicxml",
        "name": "Triplet - 6let",
        "tempos": [
          100,
          120,
          140
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th - 9let.musicxml",
        "name": "16th - 9let",
        "tempos": [
          100,
          125,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th - 8th 7let.musicxml",
        "name": "16th - 8th 7let",
        "tempos": [
          110,
          130,
          150
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Paradiddles Easy",
    "items": [
      {
        "file": "Paradiddle Builder.musicxml",
        "name": "Paradiddle Builder",
        "tempos": [
          100,
          130,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Double Paradiddle Builder.musicxml",
        "name": "Double Paradiddle Builder",
        "tempos": [
          70,
          90,
          110
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Diddle Filler.musicxml",
        "name": "Paradiddle Diddle Builder",
        "tempos": [
          80,
          100,
          120
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Pyramid.musicxml",
        "name": "Paradiddle Pyramid",
        "tempos": [
          100,
          130,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Filler.musicxml",
        "name": "Paradiddle Filler",
        "tempos": [
          100,
          130,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Diddle Pyramid.musicxml",
        "name": "Paradiddle Diddle Pyramid",
        "tempos": [
          100,
          130,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "PDD + PD.musicxml",
        "name": "PDD + PD",
        "tempos": [
          50,
          60,
          70,
          80
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Paradiddles Hard",
    "items": [
      {
        "file": "Paradiddle Builder.musicxml",
        "name": "Paradiddle Builder",
        "tempos": [
          150,
          170,
          190,
          210
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Double Paradiddle Builder.musicxml",
        "name": "Double Paradiddle Builder",
        "tempos": [
          90,
          110,
          130,
          150
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Diddle Filler.musicxml",
        "name": "Paradiddle Diddle Builder",
        "tempos": [
          100,
          120,
          140,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Pyramid.musicxml",
        "name": "Paradiddle Pyramid",
        "tempos": [
          140,
          160,
          180,
          200
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Filler.musicxml",
        "name": "Paradiddle Filler",
        "tempos": [
          150,
          170,
          190,
          210
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Paradiddle Diddle Pyramid.musicxml",
        "name": "Paradiddle Diddle Pyramid",
        "tempos": [
          150,
          170,
          190,
          210
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "PDD + PD.musicxml",
        "name": "PDD + PD",
        "tempos": [
          80,
          90,
          100,
          110
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Rolls Easy",
    "items": [
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          90,
          100,
          110
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          120,
          130
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Irish Spring.musicxml",
        "name": "Irish Spring",
        "tempos": [
          130,
          140,
          150,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Gallop.musicxml",
        "name": "Gallop",
        "tempos": [
          120,
          130,
          140
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Gallop.musicxml",
        "name": "Gallop",
        "tempos": [
          150,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet Sevens.musicxml",
        "name": "Triplet Sevens",
        "tempos": [
          100,
          115,
          130
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Triplet Sevens.musicxml",
        "name": "Triplet Sevens",
        "tempos": [
          145,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Diddle Diddle Five Nine.musicxml",
        "name": "Diddle Diddle Five Nine",
        "tempos": [
          90,
          100,
          110,
          120
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Triplet Diddle.musicxml",
        "name": "Triplet Diddle",
        "tempos": [
          90,
          105,
          120
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Triplet Diddle.musicxml",
        "name": "Triplet Diddle",
        "tempos": [
          135,
          150
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Rolls Hard",
    "items": [
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          120,
          130,
          140
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Double Beat.musicxml",
        "name": "Double Beat",
        "tempos": [
          150,
          160
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Irish Spring.musicxml",
        "name": "Irish Spring",
        "tempos": [
          140,
          155,
          170,
          180
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Gallop.musicxml",
        "name": "Gallop",
        "tempos": [
          160,
          175,
          190,
          200
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Gallop.musicxml",
        "name": "Gallop",
        "tempos": [
          215
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet Sevens.musicxml",
        "name": "Triplet Sevens",
        "tempos": [
          140,
          155,
          170
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Triplet Sevens.musicxml",
        "name": "Triplet Sevens",
        "tempos": [
          185,
          200
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Diddle Diddle Five Nine.musicxml",
        "name": "Diddle Diddle Five Nine",
        "tempos": [
          100,
          120,
          135,
          150
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Triplet Diddle.musicxml",
        "name": "Triplet Diddle",
        "tempos": [
          110,
          125,
          140
        ],
        "repetitionsPerTempo": 4
      },
      {
        "file": "Triplet Diddle.musicxml",
        "name": "Triplet Diddle",
        "tempos": [
          155,
          170
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Timing Easy",
    "items": [
      {
        "file": "16th 1 Note.musicxml",
        "name": "16th 1 Note",
        "tempos": [
          90,
          110,
          130
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th 2 Note.musicxml",
        "name": "16th 2 Note",
        "tempos": [
          90,
          110,
          130
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th 3 Note.musicxml",
        "name": "16th 3 Note",
        "tempos": [
          90,
          110,
          130
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet 1 Note.musicxml",
        "name": "Triplet 1 Note",
        "tempos": [
          110,
          125,
          140
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet 2 Note.musicxml",
        "name": "Triplet 2 Note",
        "tempos": [
          110,
          125,
          140
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet 3 Note.musicxml",
        "name": "Triplet 3 Note",
        "tempos": [
          110,
          125,
          140
        ],
        "repetitionsPerTempo": 3
      }
    ]
  },
  {
    "name": "Timing Hard",
    "items": [
      {
        "file": "16th 1 Note.musicxml",
        "name": "16th 1 Note",
        "tempos": [
          120,
          145,
          170
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th 2 Note.musicxml",
        "name": "16th 2 Note",
        "tempos": [
          120,
          145,
          170
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "16th 3 Note.musicxml",
        "name": "16th 3 Note",
        "tempos": [
          120,
          145,
          170
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet 1 Note.musicxml",
        "name": "Triplet 1 Note",
        "tempos": [
          150,
          170,
          190
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet 2 Note.musicxml",
        "name": "Triplet 2 Note",
        "tempos": [
          150,
          170,
          190
        ],
        "repetitionsPerTempo": 3
      },
      {
        "file": "Triplet 3 Note.musicxml",
        "name": "Triplet 3 Note",
        "tempos": [
          150,
          170,
          190
        ],
        "repetitionsPerTempo": 3
      }
    ]
  }
];
